### ISSUE TITLE
Binaries attached to releases

### ISSUE THREAD

**Issue by hisaac** [a7ex/xcresultparser#11] opened 2023-04-26 12:32 UTC
Would it be possible for you to add binaries to the releases here on GitHub? It would be helpful for a workflow we're using at my job.

**Comment by a7ex** [comment] 2023-04-26 22:17
Hi Isaac,
I tried to create the binary in the GitHub action, but the problem is that it is not notarised and therefore is not really safe to run on a different machine.
Last time I tried notarising another app I was not very successful.
Do you have any hints?

**Comment by a7ex** [comment] 2023-04-27 17:31
The actions have attachments. The attachment is the binary. You can try those. They are not notarised and thus from "an unknown source". Not exactly, what I would want to publish.
Therefore I distribute it as source and `brew` takes care of the rest.
We use `brew` our buildchains. Why can't you download and build from source or have `brew` handle that for you?

**Comment by hisaac** [comment] 2023-04-27 19:31
Gotcha, I'll do some experimentation on my branch and see if I can come up with something workable.

As for using `brew`, for our build system, I prefer to download specific versions of our tools so we know exactly what we're getting. `brew` doesn't allow for that, unfortunately. That'd make life way easier.

**Comment by hisaac** [comment] 2023-04-27 20:23
ok, I did a bit of a deep-dive on this notarization thing, and have learned some interesting information!

So when you download a binary using a browser, the browser adds "quarantine flags" to the item, which tells macOS that the user has to explicitly approve running it, hence the "an unknown source" popup.

BUT, there are a few workarounds:

1. If you download the item using `curl` or `wget` or similar, it does not set those quarantine flags.
2. If the item being downloaded is a tarball — .tar, .tar.gz, .tar.xz, etc. — unarchiving that using the `tar` binary strips off the quarantine flags.
3. You can explicitly remove the quarantine flags after downloading by running the following command:
    ```shell
    xattr -rd com.apple.quarantine "/path/to/xcresultparser"
    ```

All that said, perhaps a good way forward would be to archive the binary as a tarball for the release artifacts, and add a note to the README summarizing what I've got above. What do you think? I'm interested enough to do said work if you're open to the change.

**Comment by hisaac** [comment] 2023-04-27 20:25
Also, side note, I'd recommend also archiving the Actions artifacts prior to uploading them. The `upload-artifact` action has an annoying side effect of stripping some data from the files, namely in this case, the binaries executable permissions — as in, you have to `chmod +x xcresultparser` the downloaded binary.

The [suggested workaround](https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files) is to archive as a tarball prior to uploading.

**Comment by hisaac** [comment] 2023-04-28 10:29
I see you got it notarized! Even better! 🙌

Can I ask how you did it? I couldn't figure it out from my googling around.

**Comment by a7ex** [comment] 2023-04-28 13:28
There is no a shell script in the Repo. Code tells so much more than words... :-)

**Comment by hisaac** [comment] 2023-04-28 13:33
Oh I don't see the shell script 🤔

**Comment by a7ex** [comment] 2023-04-28 13:37
ups...?
Did I only dreamed I committed - again... :-)

**Comment by a7ex** [comment] 2023-04-28 13:43
There you go...

**Closed** 2023-04-28 14:42 UTC

**Comment by a7ex** [comment] 2023-04-28 15:42
You are very welcome.
I am glad, that my little tool ist useful for you.

And in fact it plays an important role in our build chain, not only to display the tests, but more important to send the results to sonarqube with coverage and testresults. For the former there is a tool, which is just very slow, but for the latter (sending test results) there is nothing, because xcresult is not compatible out of the box.

**Comment by hisaac** [comment] 2023-04-28 15:54
Nice, we're using it in a similar fashion. We're now pre-converting our code coverage from .xcresult to Cobertura XML before sending it to [Codecov](https://codecov.io). Codecov does do the conversion for us if we just sent the .xcresult, but it's _way_ slower than doing it ahead of time using xcresultparser. 🚀
