### ISSUE TITLE
Xcode 16 beta 3 tests fail as xcresulttool get object is deprecated

### ISSUE THREAD

**Issue by mikehouse** [a7ex/xcresultparser#39] opened 2024-07-09 09:10 UTC
Hi.
The issue the same as here https://github.com/fastlane/fastlane/issues/22132

These commands are okay

```bash
~ xcodebuild -version
Xcode 15.4
Build version 15F31d

~ ./scripts/xcresultparser -o cli /fastlane/test_output/Test-MyApp-2024.07.09_14-57-50-339029-+0700.xcresult
```

These commands are not okay

```bash
~ xcodebuild -version
Xcode 16.0
Build version 16A5202i

~ ./scripts/xcresultparser -o cli /fastlane/test_output/Test-MyApp-2024.07.09_14-57-50-339029-+0700.xcresult
Error: This command is deprecated and will be removed in a future release, --legacy flag is required to use it.
Usage: xcresulttool get object [--legacy] --path <path> [--id <id>] [--version <version>] [--format <format>]
  See 'xcresulttool get object --help' for more information.
Error: argumentError
```

Thanks for awesome tool, we use it every day on our CI pipelines.

**Comment by a7ex** [comment] 2024-07-09 15:04
Thanks for the heads up. I will look into asap.

**Comment by mangerlahn** [comment] 2024-07-10 07:38
The issue is with XCResultKit actually. It calls `xcrun xcresulttool get/export`, which are deprecated with `xcresulttool` shipped in Xcode 16 beta 3.

**Comment by a7ex** [comment] 2024-07-10 07:51
I know. But I will need to investigate, whether I can use xcresultkit in another way or at least give the xcresulttool developers a heads up. Or even consider to ditch xcresulttool...

**Comment by mangerlahn** [comment] 2024-07-10 08:32
I have prepared a pull request that adds a temporary workaround: https://github.com/davidahouse/XCResultKit/pull/52

The old/existing commands on `xcresulttool` will continue to work if a —legacy option is added.

**Comment by Brett-Best** [comment] 2024-07-10 08:35
It's rather annoying that Apple didn't provide an environment variable option.
Some of the new commands looks like we could use however seems to be missing a way to get the warnings from the report unfortunately.

**Comment by Brett-Best** [comment] 2024-07-23 13:56
@a7ex https://github.com/davidahouse/XCResultKit/pull/52 is merged now, would we be able to bump the package to use it?

**Comment by a7ex** [comment] 2024-07-23 16:00
Sure, will do that later after work.
Stay tuned! :-)

**Comment by a7ex** [comment] 2024-07-23 22:05
There is no new tag.
I am waiting for David to make a new tag, so I can update my Package.swift.

Is it so urgent, that we can not wait for the tag an would now reference the commit hash?
No…is it?

It’s all still beta early days… I am sure, David will soon make a tag for a new release.

As far as I understand this is anyway only a temporary solution. Once Apple really deprecates the old API, we will need to change a bit more.
As far as I could see, that JSON objects are much simpler and nicer AND way smaller. But they also seem to lack information, which we had before with the now deprecated method.
But we will see. Maybe the information is hidden behind some switches to the new API calls :-)

**Comment by Brett-Best** [comment] 2024-07-24 23:16
All good, I've made https://github.com/a7ex/xcresultparser/pull/40 which I'll update when a tag is made 😄 

Yeah, I think the test summary part looks okay?
But getting compile warnings/errors doesn't look okay so probably should raise a feedback with Apple about that removed functionality which I find really useful 😢

**Comment by a7ex** [comment] 2024-07-25 12:47
Thank you Brett. I have a few refactoring for Swift 6 compatibility as well. I will add them also to the "Xcode 16 compatibility release" :-)

**Closed** 2024-07-31 14:00 UTC
